name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk \
        autoconf automake libtool m4 pkg-config cmake build-essential \
        libffi-dev libssl-dev

    - name: Install Python tools
      run: |
        pip install --upgrade pip setuptools wheel
        pip install cython==0.29.36
        pip install buildozer

    - name: Setup Android SDK
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools

        curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip sdk.zip
        mv cmdline-tools latest

        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

        yes | sdkmanager --licenses

        sdkmanager "platform-tools" \
                   "platforms;android-33" \
                   "build-tools;33.0.2"

    - name: Build APK
      run: |
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
